### ISSUE TITLE
After upgrade to latest Hangfire version (1.7.28) dropdowns are not working anymore

### ISSUE THREAD

**Issue by timdhaeyer** [lcourson/Hangfire.Dashboard.Management.v2#17]
Hi,

I after upgrading the nuget packages in my solution to the latest version of Hangfire (1.7.28), I noticed that none of the dropdowns are working anymore.
Both the dropdowns that are used for Enum input data and the dropdown for the task type.
The dropdown opens, but when you want to select another option, it just keeps showing the default.

For now, I can revert back to an older version of Hangfire. But can you please check what the problem is so that we can stay up-to-date with further package updates?

Kind Regards
Tim

**Comment by NSiggel** [comment]
Hey Tim,

So just noticed similar issue on my side as well. I am guessing the is due to an error in referencing JQUERY input mask libraries, since these are the 404 errors and subsequent JS Errors I am seeing
![image](https://user-images.githubusercontent.com/11523121/150412649-2f0515da-3e45-4eac-ac56-c0ef8702f981.png)

I'm not sure on the best way to fix them at the moment, since in they are part of the src, but not sure why not available at runtime.
https://github.com/lcourson/Hangfire.Dashboard.Management.v2/tree/master/src/Content/Libraries/inputmask

I'm experiencing broken menus in 1.7.27 and 1.7.28, what version did you have to revert to get it to work properly ?

**Comment by timdhaeyer** [comment]
I went back to 1.7.19. Which was the version I had before I tried the upgrade.

**Comment by lcourson** [comment]
The latest version 2.2.0 (pushed today) should now be using 1.7.28.  Please try updating your package and see if it work for you.

**Comment by NSiggel** [comment]
Hey @lcourson thanks for  the update, automated management pages seem to be working properly now for using the automated types and timings buttons, much appreciate the update.

I am however seeing a new little bug, where in trying to queue a job, I see the following error message pop up in the UI.
The interesting thing is the job does get scheduled and execute without any error, so it just seems to be some form of validation error / on the JS of the return API ? (Dummy parameters and name in screenshot)
![image](https://user-images.githubusercontent.com/11523121/153615188-ca87199a-eb9e-454d-9e5b-bbeb81314968.png)

Just wanted to report as causing some confusion for users, when jobs are actually seemingly being scheduled properly.

**Comment by timdhaeyer** [comment]
Hi @lcourson,

I tried updating my packages, but I still get the same issue with dropdown boxes. Should I take any other steps while upgrading?

**Comment by lcourson** [comment]
sorry for the long delay in getting back to you, but I have pushed a new version of the nuget package that should fix the CSP/dropdown issues.  Please take a look and see if it fixes your issues.
